theme: minima

# 插件管理
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 数据源配置
data_source: _data

# 导航配置
include:
  - navigation.yml

# 构建配置
markdown: kramdown
highlighter: rouge

# 开发服务器配置
development:
  host: 127.0.0.1
  port: 4000
  show_dir_listing: false

# 基础配置
title: 我的Jekyll网站
description: 基于Jekyll构建的静态站点
url: "https://liangrui198.github.io"  # 必须包含协议头
baseurl: ""  # 必须保持为空值

# 主题配置
theme: minima