# Configurations
title:            大数据技术栈分享
longtitle:        hadoop,spark,hive,ambari,kdc
author:           Roy liang
email:            liangrui198@gmail.com
description: >
  hello gitbook

version:          1.0
gitbook_version:  1.0.0

url:              'https://liangrui198.github.io'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     liangrui198.github.io/assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow
include:
 - assets
  - _sass
  - _includes
  - _layouts
  - _posts

exclude:
  - _drafts


collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
  categories:
    output: true  # 为每个分类生成独立页面
    permalink: /categories/:name/  # 自定义分类页URL
  hadoop:
    output: true
    permalink: /hadoop/:path/
  spark: 
    output: true
    permalink: /spark/:path/  
  

# 默认分类设置
defaults:
  - scope:
      path: ""
      type: categories
    values:
      layout: category

ordered_collections:
  - posts
  - pages
  - others
  - kerberos

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
