# Jekyll 配置文件

# 站点设置
# 这些变量可在模板中通过 {{ site.title }} 等方式访问

title: 博客记录
email: 1067165280@qq.com
description: >-
  博客是用jekyll默认主题构建的，用于记录大数据相关知识。
baseurl: "" # 站点子路径，如 /blog
url: "" # 站点主域名，如 http://example.com
twitter_username: twiter
github_username:  liangrui198
title: 博客记录

# 构建设置
theme: minima

# 代码高亮设置
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除不处理的文件和文件夹
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

show_excerpts: true

include:
  - assets